server.port=${SERVER_PORT:3000}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:order_db}
spring.datasource.username=${POSTGRES_USER:groupf}
spring.datasource.password=${POSTGRES_PASSWORD:groupf}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:groupf}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:groupf}

rabbitmq.exchange.order=order.exchange
rabbitmq.queue.order=order.queue
rabbitmq.queue.notification-order=notification.order.queue
rabbitmq.routing-key.order=order.created
rabbitmq.routing-key.order-created=order.created

product.service.url=${PRODUCT_SERVICE_URL:http://groupf_product_service:3001}